# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/parkour.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParkourRecorder(object):
    def setupUi(self, ParkourRecorder):
        ParkourRecorder.setObjectName("ParkourRecorder")
        ParkourRecorder.setEnabled(True)
        ParkourRecorder.resize(691, 299)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParkourRecorder.sizePolicy().hasHeightForWidth())
        ParkourRecorder.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ParkourRecorder)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main.setSpacing(5)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.verticalLayout_controls = QtWidgets.QVBoxLayout()
        self.verticalLayout_controls.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_controls.setObjectName("verticalLayout_controls")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_subj_details = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.lbl_subj_details.setFont(font)
        self.lbl_subj_details.setObjectName("lbl_subj_details")
        self.horizontalLayout.addWidget(self.lbl_subj_details)
        self.linedit_subjname = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.linedit_subjname.setFont(font)
        self.linedit_subjname.setObjectName("linedit_subjname")
        self.horizontalLayout.addWidget(self.linedit_subjname)
        self.verticalLayout_controls.addLayout(self.horizontalLayout)
        self.btn_startstop_expt = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.btn_startstop_expt.setFont(font)
        self.btn_startstop_expt.setObjectName("btn_startstop_expt")
        self.verticalLayout_controls.addWidget(self.btn_startstop_expt)
        self.lbl_tasks = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_tasks.setFont(font)
        self.lbl_tasks.setObjectName("lbl_tasks")
        self.verticalLayout_controls.addWidget(self.lbl_tasks)
        self.listTasks = QtWidgets.QListWidget(self.centralwidget)
        self.listTasks.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.listTasks.setFont(font)
        self.listTasks.setObjectName("listTasks")
        self.verticalLayout_controls.addWidget(self.listTasks)
        self.horizontalLayout_main.addLayout(self.verticalLayout_controls)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plain_instructions = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.plain_instructions.setFont(font)
        self.plain_instructions.setReadOnly(True)
        self.plain_instructions.setPlainText("")
        self.plain_instructions.setObjectName("plain_instructions")
        self.verticalLayout.addWidget(self.plain_instructions)
        self.horizontalLayout_main.addLayout(self.verticalLayout)
        self.verticalLayout_video = QtWidgets.QVBoxLayout()
        self.verticalLayout_video.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_video.setSpacing(6)
        self.verticalLayout_video.setObjectName("verticalLayout_video")
        self.lbl_message = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_message.sizePolicy().hasHeightForWidth())
        self.lbl_message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.lbl_message.setFont(font)
        self.lbl_message.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 25 20pt \"Bahnschrift Light\";")
        self.lbl_message.setObjectName("lbl_message")
        self.verticalLayout_video.addWidget(self.lbl_message)
        self.lbl_img = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        self.lbl_img.setFont(font)
        self.lbl_img.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_img.setObjectName("lbl_img")
        self.verticalLayout_video.addWidget(self.lbl_img)
        self.lbl_datetime = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_datetime.sizePolicy().hasHeightForWidth())
        self.lbl_datetime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_datetime.setFont(font)
        self.lbl_datetime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_datetime.setObjectName("lbl_datetime")
        self.verticalLayout_video.addWidget(self.lbl_datetime)
        self.lbl_exptdur = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_exptdur.sizePolicy().hasHeightForWidth())
        self.lbl_exptdur.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_exptdur.setFont(font)
        self.lbl_exptdur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_exptdur.setObjectName("lbl_exptdur")
        self.verticalLayout_video.addWidget(self.lbl_exptdur)
        self.horizontalLayout_main.addLayout(self.verticalLayout_video)
        self.horizontalLayout_main.setStretch(0, 2)
        self.horizontalLayout_main.setStretch(1, 4)
        self.horizontalLayout_main.setStretch(2, 8)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_main)
        ParkourRecorder.setCentralWidget(self.centralwidget)
        self.act_new_subj = QtWidgets.QAction(ParkourRecorder)
        self.act_new_subj.setObjectName("act_new_subj")

        self.retranslateUi(ParkourRecorder)
        QtCore.QMetaObject.connectSlotsByName(ParkourRecorder)

    def retranslateUi(self, ParkourRecorder):
        _translate = QtCore.QCoreApplication.translate
        ParkourRecorder.setWindowTitle(_translate("ParkourRecorder", "Parkour Recorder"))
        self.lbl_subj_details.setText(_translate("ParkourRecorder", "Subject:"))
        self.btn_startstop_expt.setText(_translate("ParkourRecorder", "Start Experiment"))
        self.lbl_tasks.setText(_translate("ParkourRecorder", "List of tasks:"))
        self.label.setText(_translate("ParkourRecorder", "Instructions"))
        self.lbl_message.setText(_translate("ParkourRecorder", "Expt messages"))
        self.lbl_img.setText(_translate("ParkourRecorder", "Video Stream"))
        self.lbl_datetime.setText(_translate("ParkourRecorder", "Date time"))
        self.lbl_exptdur.setText(_translate("ParkourRecorder", "Expt duration"))
        self.act_new_subj.setText(_translate("ParkourRecorder", "New subject"))
        self.act_new_subj.setToolTip(_translate("ParkourRecorder", "Create a new subject"))

